#!/bin/bash
# SessionStart hook: inject startup context into the session
# stdout → Claude's context window

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"

echo "=== SESSION CONTEXT ==="

if [ -f "$PROJECT_DIR/tasks/plan.md" ]; then
  echo "--- plan.md ---"
  head -50 "$PROJECT_DIR/tasks/plan.md" | head -c 4000
fi

echo ""

if [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
  echo "--- lessons.md ---"
  head -50 "$PROJECT_DIR/tasks/lessons.md"
fi

echo ""

if [ -f "$PROJECT_DIR/docs/memory-map.md" ]; then
  echo "--- memory-map.md ---"
  sed -n '/mir:generated:start/,$p' "$PROJECT_DIR/docs/memory-map.md" | head -30
fi

echo ""

# Latest session snapshot (if exists) — use find to avoid glob expansion issues
LATEST_SESSION=$(find "$PROJECT_DIR/tasks/sessions" -name "*.md" -type f 2>/dev/null | sort -r | head -1)
if [ -n "$LATEST_SESSION" ] && [ -f "$LATEST_SESSION" ]; then
  echo "--- latest session ---"
  head -50 "$LATEST_SESSION"
fi

echo ""

LATEST_RUNNER=$(find "$PROJECT_DIR/tasks/runner" -name "*.md" -type f 2>/dev/null | sort -r | head -1)
if [ -n "$LATEST_RUNNER" ] && [ -f "$LATEST_RUNNER" ]; then
  echo "--- latest runner ---"
  awk '/artifacts:/{exit} {print}' "$LATEST_RUNNER" | head -20
fi

echo "=== END SESSION CONTEXT ==="

# mir:profile:enforcement:begin
# Generated by Mir Profile Compiler (tools/profile_compiler). DO NOT EDIT MANUALLY.
# Source: .mir/repo-profile.toml — edit profile and recompile to update this block.
# Role policy reminder injected into session-start for family: mir-harness
MIR_CODEX_DEFAULT_ENABLED="true"
echo "[mir] role policy active: claude=control_plane codex=code_tdd_review_plane codex_default=$MIR_CODEX_DEFAULT_ENABLED family=mir-harness" >&2
if [ -n "${MIR_CODEX_SESSION_ID:-}" ]; then
    echo "[mir] active codex session: $MIR_CODEX_SESSION_ID modes=$MIR_CODEX_ALLOWED_MODES" >&2
elif [ "$MIR_CODEX_DEFAULT_ENABLED" = "true" ]; then
    echo "[mir] no active codex session — code edits in code_paths will be blocked by pre-tool-use hook" >&2
fi

# mir:profile:enforcement:end
