#!/bin/bash
# SessionStart hook: inject startup context into the session
# stdout → Claude's context window
# tier: warn — info only, never blocks (R27-T02 / Choice 5=A)
# ADR-53 D1: current-only core — upfront context + plan head + lessons head.
#   Dropped: memory-map.md sed tail, latest-session, latest-runner slices.
#   Byte-guard: total stdout capped at 10240 bytes.
_MIR_HOOK_TIER="warn"

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"

# Accumulate output in a variable; truncate to 10240 bytes before writing.
_OUT=""

_OUT+="=== SESSION CONTEXT ===
"

if [ -f "$PROJECT_DIR/scripts/build_session_upfront_context.py" ]; then
  _UPFRONT=$(python3 "$PROJECT_DIR/scripts/build_session_upfront_context.py" "$PROJECT_DIR" 2>/dev/null)
  _OUT+="=== UPFRONT CONTEXT ===
${_UPFRONT}
=== END UPFRONT CONTEXT ===

"
fi

if [ -f "$PROJECT_DIR/tasks/plan.md" ]; then
  _OUT+="--- plan.md ---
"
  _OUT+="$(head -c 1200 "$PROJECT_DIR/tasks/plan.md")
"
fi

_OUT+="
"

_DB_PATH="$PROJECT_DIR/.mir/memory.db"
if [ -f "$_DB_PATH" ]; then
  _LESSONS=$(python3 - "$_DB_PATH" 2>/dev/null <<'PYEOF'
import sys, sqlite3
db_path = sys.argv[1]
try:
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        """
        SELECT e.slug, f.object_literal
          FROM facts f
          JOIN entities e ON e.id = f.subject_entity_id
         WHERE f.predicate = 'lesson'
           AND f.status    = 'active'
         ORDER BY f.id DESC
         LIMIT 15
        """
    ).fetchall()
    conn.close()
    for slug, text in rows:
        print(f"- **{slug}**: {text}")
except Exception:
    sys.exit(1)
PYEOF
)
  _DB_EXIT=$?
  if [ "$_DB_EXIT" -eq 0 ] && [ -n "$_LESSONS" ]; then
    _OUT+="--- lessons (DB-live, active only) ---
${_LESSONS}
"
  elif [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
    _OUT+="--- lessons.md ---
$(head -30 "$PROJECT_DIR/tasks/lessons.md")
"
  fi
elif [ -f "$PROJECT_DIR/tasks/lessons.md" ]; then
  _OUT+="--- lessons.md ---
$(head -30 "$PROJECT_DIR/tasks/lessons.md")
"
fi

_OUT+="
Context depth on demand: mir context pull \"<query>\" (--history for archived/expired)
=== END SESSION CONTEXT ===
"


# 10240-byte hard guard: truncate with marker if needed.
# A1 fix: measure bytes (UTF-8) not characters. ${#var} counts chars which
# underestimates multibyte (e.g. Korean) content in a UTF-8 locale.
_BYTE_LIMIT=10240
_MARKER="
[context truncated at ${_BYTE_LIMIT} bytes — use mir context pull for details]
"
_BYTE_LEN=$(printf '%s' "$_OUT" | wc -c | tr -d ' \t')
if [ "$_BYTE_LEN" -gt "$_BYTE_LIMIT" ]; then
  # Marker byte length (measured via wc -c, same as _BYTE_LEN above).
  _MARKER_LEN=$(printf '%s' "$_MARKER" | wc -c | tr -d ' \t')
  _CUT_AT=$(( _BYTE_LIMIT - _MARKER_LEN ))
  # Slice by bytes via python3 — bash ${var:0:N} slices chars, not bytes.
  _OUT=$(printf '%s' "$_OUT" | python3 -c "
import sys
data = sys.stdin.buffer.read()
cut = data[:$_CUT_AT].decode('utf-8', errors='ignore')
sys.stdout.write(cut)
")
  _OUT="${_OUT}${_MARKER}"
fi

printf '%s' "$_OUT"

# mir:profile:enforcement:begin
# Generated by Mir Profile Compiler (tools/profile_compiler). DO NOT EDIT MANUALLY.
# Source: .mir/repo-profile.toml — edit profile and recompile to update this block.
# Role policy reminder injected into session-start for family: your-harness
MIR_CODEX_DEFAULT_ENABLED="true"
echo "[mir] role policy active: claude=control_plane codex=code_tdd_review_plane codex_default=$MIR_CODEX_DEFAULT_ENABLED family=your-harness" >&2
if [ -n "${MIR_CODEX_SESSION_ID:-}" ]; then
    echo "[mir] active codex session: $MIR_CODEX_SESSION_ID modes=$MIR_CODEX_ALLOWED_MODES" >&2
elif [ "$MIR_CODEX_DEFAULT_ENABLED" = "true" ]; then
    echo "[mir] no active codex session — code edits in code_paths will be blocked by pre-tool-use hook" >&2
fi

# mir:profile:enforcement:end
