#!/bin/bash
_MIR_HOOK_TIER="warn"
_mir_session_body() {
# SessionStart hook: inject startup context into the session
# stdout → Claude's context window
# ADR-53: task-blind startup includes only repository identity, mandatory safety,
# and an on-demand retrieval hint. Task-specific context is pulled after classification.

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"

# SessionStart is read-only. Cursor cleanup is an explicit operator task; startup must
# never mutate tasks/plan.md or create archive files in either main or delegated worktrees.

echo "=== SESSION CONTEXT ==="

if [ -f "$PROJECT_DIR/scripts/build_session_upfront_context.py" ]; then
  _UPFRONT=$(python3 "$PROJECT_DIR/scripts/build_session_upfront_context.py" "$PROJECT_DIR" 2>/dev/null)
  echo "$_UPFRONT"
  echo ""
else
  echo "repository_profile: unavailable"
  echo "mandatory_safety: inspect repository-local instructions before mutation"
  echo "Context depth on demand: uv run mir context pull \"<query>\" (--history for archived/expired)"
  echo ""
fi

# ADR-55 doc-size advisory guard (review major docs)
# A3 2026-06-28: ${CLAUDE_PROJECT_DIR:-.} so the guard also fires under a Codex main (CLAUDE_PROJECT_DIR unset).
if command -v uv >/dev/null 2>&1 && [ -f "${CLAUDE_PROJECT_DIR:-.}/config/doc-size-guard.json" ]; then
  _DG=$(cd "${CLAUDE_PROJECT_DIR:-.}" && uv run mir doc-guard --config config/doc-size-guard.json --project-dir "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null) || true
  [ -n "$_DG" ] && echo "$_DG"
fi

# mir:profile:enforcement:begin
# Generated by Mir Profile Compiler (tools/profile_compiler). DO NOT EDIT MANUALLY.
# Source: .mir/repo-profile.toml — edit profile and recompile to update this block.
# Role policy reminder injected into session-start for family: your-harness
MIR_CODEX_DEFAULT_ENABLED="true"
echo "[mir] role policy active: main_agent_parity=claude_codex delegated_backend=codex_first codex_backend=code_tdd_review_plane codex_default=$MIR_CODEX_DEFAULT_ENABLED family=your-harness" >&2
if [ -n "${MIR_CODEX_SESSION_ID:-}" ]; then
    echo "[mir] active codex session: $MIR_CODEX_SESSION_ID modes=$MIR_CODEX_ALLOWED_MODES" >&2
elif [ "$MIR_CODEX_DEFAULT_ENABLED" = "true" ]; then
    echo "[mir] no active codex session — delegated execution is available when isolation, review independence, or parallelism justifies its cost; bounded direct-main code_path edits remain allowed" >&2
fi

# mir:profile:enforcement:end

}

# Snapshot global Claude/Codex config files into a local git history repo.
# Runs silently; always exits 0; must not add to injected context bytes.
timeout 10 bash "${CLAUDE_PROJECT_DIR:-.}/scripts/backup_global_claude_config.sh" >/dev/null 2>&1 || true

# mir:f3:stdout-cap:begin
# token-efficiency F3 (2026-06-10): template-parity 10,240B stdout cap (UTF-8 safe).
_mir_session_body "$@" | python3 -c '
import sys
data = sys.stdin.buffer.read()
limit = 10240
if len(data) <= limit:
    sys.stdout.buffer.write(data)
else:
    cut = data[: limit - 64].decode("utf-8", errors="ignore")
    sys.stdout.write(cut + "\n[mir] session-start context truncated at 10KB (F3 cap)\n")
'
# mir:f3:stdout-cap:end
