"""TaskSpec — task intent (v0.5 final).

design §4.1.4 · Q2 5 required + 6 optional + extensions.
Harness B Hook #1 (`taskspec_validate.py`) validates against this schema.
"""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class TaskSpec(BaseModel):
    """Single task specification generated by Conductor from natural-language instructions.

    frozen=True: From the moment Compile references this as ``CompiledJob.spec``,
    TaskSpec must be immutable so the audit chain is reproducible. Retries must
    create a new instance with ``model_copy(update=…)``.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    # === required (5) ===
    intent: str = Field(
        min_length=1,
        max_length=8000,
        description="Natural-language summary of the user intent. Extracted by Conductor from the Discord message.",
    )
    scope: tuple[str, ...] = Field(
        min_length=1,
        description="Target file glob or module path (for example, 'src/core/**').",
    )
    success_criteria: tuple[str, ...] = Field(
        min_length=1,
        description="Observable completion criteria (for example, 'tests pass', 'lint=0'). Evidence for intent verification.",
    )
    role_binding: str = Field(pattern=r"^(executor|reviewer|planner|tester)$")
    budget: dict[str, int] = Field(
        description="{tokens, time_sec, retries}. Merged with env.budget_defaults during Engine compile.",
    )

    # === optional (6) ===
    target_files: tuple[dict, ...] = ()          # [{path, inode?, sha256?}]  — fixed at compile time
    expected_symbols: tuple[str, ...] = ()       # for function/class/module verification
    required_tools: tuple[str, ...] = ()         # your-harness MCP tool allowlist subset
    stack: str | None = None                     # "python" / "flutter" / ... (guides.toml mapping)
    parent_task_id: int | None = None            # retry / child-task linkage
    fingerprint: str | None = None               # Discord event canonical_json sha256 (R4 TOCTOU)

    # === v0.6 ADR 3 Phase gate ===
    phase_tag: str | None = None
    """Target phase id for Hook #3 ``check_phase_gate`` (ADR 3 §2.5).

    Conductor.ingress infers via the 4-step priority (CLI flag → literal
    regex ``(?i)phase[- ]?(\\d+)`` → label token 2+ match → current_phase
    fallback). ``None`` means the request is not phase-scoped — gate passes
    without checking preceding phases.

    Self-review H1: field added in v0.6. Pre-existing TaskSpec JSON
    (v0.5) loads cleanly because the default is ``None`` and the model
    keeps ``extra='forbid'`` on every other field."""

    # === extensions — harness reads only ===
    extensions: dict[str, Any] = Field(default_factory=dict)
