"""Cross-platform coordinator for a ready Mir project baseline."""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import io
import json
import os
import platform
import re
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

from mir.core.config.loader import ConfigLoadError, load_config, resolve_memory_db
from mir.core.engine.memory import store

from . import context as context_cli
from . import memory as memory_cli

_PROFILE_CHOICES = ("code_app", "hybrid_pipeline", "infra_runtime", "content_workspace")
_PROFILE_ALIASES = {"hybrid": "hybrid_pipeline", "infra": "infra_runtime"}
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")
_ARCHITECTURE_OUTPUTS = ("spec/STATE.md", "spec/index.yaml", "spec/graph.yaml")
_ARCHITECTURE_SEQUENCE = ("mir-core:design", "mir-core:spec-architect")


def _parse(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="mir bootstrap")
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--slug", default=None)
    parser.add_argument("--profile", default="code_app")
    parser.add_argument("--json", action="store_true", default=False, dest="json")
    parser.add_argument(
        "--finalize",
        action="store_true",
        default=False,
        help="phase 2: verify capabilities after restarting the agent runtime",
    )
    parser.add_argument(
        "--architecture-initialized",
        action="store_true",
        default=False,
        help="attest that mir-core:design then mir-core:spec-architect initialized the project",
    )
    parser.add_argument(
        "--skip-capability-activation",
        action="store_true",
        default=False,
        help="test/development only: leave bootstrap incomplete unless --allow-incomplete",
    )
    parser.add_argument(
        "--allow-incomplete",
        action="store_true",
        default=False,
        help=argparse.SUPPRESS,
    )
    return parser.parse_args(argv)


def _normalise_slug(raw: str) -> str:
    slug = re.sub(r"[^a-z0-9_-]+", "-", raw.strip().lower()).strip("-_")
    if not _SLUG_RE.fullmatch(slug):
        raise ValueError(f"project slug {raw!r} cannot be normalized to a valid slug")
    return slug


def _memory_config_text(slug: str) -> str:
    return f'''# Active portable memory baseline. Managed by `mir bootstrap` when absent.

[memory]
enabled = true
required = true
backend = "sqlite_fts5"
db_path = ".mir/memory.db"
vector_mode = "off"
plugin_mode = "disabled"
recall_policy = "progressive"

[memory.embedding]
enabled = false
required = false

[[memory.external_archives]]
slug = "{slug}-docs"
root = "docs"
mode = "indexed"
glob_include = ["**/*.md"]

[[memory.external_archives]]
slug = "{slug}-tasks"
root = "tasks"
mode = "indexed"
glob_include = ["**/*.md"]

[[memory.external_archives]]
slug = "{slug}-rules"
root = ".ai-harness"
mode = "indexed"
glob_include = ["**/*.md"]
'''


def _repo_profile_text(slug: str, profile: str) -> str:
    return f'''# Repository identity generated by `mir bootstrap`.

[repo]
slug = "{slug}"
display_name = "{slug.replace("-", " ").title()}"
path = "."
repository_type = "starter_project"
rollout_class = "bootstrap_only"
overlay_archetype = "template_transitional"
status = "active"
purpose = "Describe this repository's purpose."
technology_stack = []
profile_base_commit = "unverified"
profile_verified_at = ""

[ownership]
main_role = "control_plane"
delegated_execution = "codex_first"
main_agent_contract = "shared_parity"
codex_backend_role = "code_tdd_review_plane"
codex_default_enabled = true
allow_role_override = true
override_requires_record = true

[paths]
code_paths = ["src/", "scripts/", "tools/"]
non_code_paths = ["docs/", "tasks/", ".ai-harness/", "README.md", "CLAUDE.md", "AGENTS.md"]
protected_paths = [".env", ".env.*", "secrets/**", ".mir/memory.db*"]
generated_paths = ["AGENTS.md", ".codex/**", "docs/memory-map.md", "tasks/lessons.md"]
architecture_refs = ["ARCHITECTURE.md", "docs/decisions/"]
configuration_paths = ["pyproject.toml", "config/"]
verification_paths = ["tests/"]
workflow_refs = ["CLAUDE.md", ".ai-harness/", ".claude/", "tasks/plan.md"]
exception_refs = [".mir/boundary.md", ".mir-preserve.toml"]

[preserve]
skills = []
claude_sections = []
agent_memory_paths = [".mir/memory.db"]
commands = []
extra_docs = []

[boundaries]
live_runtime = []
secrets = [".env", ".env.*", "secrets/**"]
data_sensitivity = "low"
release_window = "anytime"
external_services = []

[execution]
delegated_execution_contract = "subagents_codex_first"
delegation_required_tasks = ["adopter_wide_template_contract_or_bootstrap_change", "release_review"]
delegation_recommended_tasks = ["implementation", "tests", "independent_review"]
main_direct_tasks = ["small_documentation_change", "configuration_inspection", "final_judgment"]
codex_allowed_modes = ["code", "review", "tdd"]
codex_blocked_modes = []
review_scope = ["src/", "scripts/", "tools/", "tests/"]
tdd_scope = ["src/", "scripts/", "tools/"]
non_code_profile = "{profile}"

[gates]
requires_phase_gate = false
requires_secrets_vault = false
requires_dynamic_egress = false
requires_release_window = false
requires_external_store = true
requires_memory_store = true
requires_global_capabilities = true
'''


def _validate_existing_profile(path: Path) -> None:
    try:
        with path.open("rb") as handle:
            raw = tomllib.load(handle)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ValueError(f"invalid existing .mir/repo-profile.toml: {exc}") from exc
    gates = raw.get("gates", {})
    if (
        gates.get("requires_memory_store") is not True
        or gates.get("requires_global_capabilities") is not True
    ):
        raise ValueError(
            "existing .mir/repo-profile.toml must explicitly set "
            "[gates].requires_memory_store=true and requires_global_capabilities=true; "
            "bootstrap will not overwrite authored policy"
        )


def _ensure_authored_files(root: Path, slug: str, profile: str) -> None:
    (root / ".mir").mkdir(parents=True, exist_ok=True)
    (root / "docs").mkdir(parents=True, exist_ok=True)
    (root / "tasks").mkdir(parents=True, exist_ok=True)
    (root / ".ai-harness").mkdir(parents=True, exist_ok=True)

    harness_path = root / "harness_a.toml"
    if not harness_path.exists():
        _atomic_write_text(harness_path, _memory_config_text(slug))

    profile_path = root / ".mir" / "repo-profile.toml"
    if not profile_path.exists():
        _atomic_write_text(profile_path, _repo_profile_text(slug, profile))

    tdd_path = root / "tasks" / "tdd.json"
    if not tdd_path.exists():
        _atomic_write_text(tdd_path, '{\n  "version": 1,\n  "changes": []\n}\n')
    plan_path = root / "tasks" / "plan.md"
    if not plan_path.exists():
        _atomic_write_text(plan_path, "# Plan\n\nNo active work.\n")


def _load_capability_sources(root: Path, profile: str) -> dict:
    path = root / "config" / "capability-sources.json"
    if not path.is_file():
        raise ValueError("tracked config/capability-sources.json is missing")
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid config/capability-sources.json: {exc}") from exc
    if not isinstance(raw, dict) or not raw:
        raise ValueError("config/capability-sources.json must be a non-empty JSON object")
    source = raw.get("source")
    profiles = raw.get("profiles")
    if not isinstance(source, dict) or not source.get("url") or not source.get("ref"):
        raise ValueError("capability source must declare source.url and source.ref")
    if not isinstance(profiles, dict) or not profiles:
        raise ValueError("capability source must declare non-empty profiles")
    packs = profiles.get("packs")
    aliases = profiles.get("aliases", {})
    selected = aliases.get(profile, profile) if isinstance(aliases, dict) else profile
    if not isinstance(packs, dict) or selected not in packs:
        raise ValueError(f"capability source has no pack for profile {profile!r}")
    return raw


def _activate_capabilities(root: Path, profile: str) -> tuple[str, dict]:
    try:
        from . import capability as capability_cli
    except ImportError as exc:
        return "failed", {"reason": f"capability CLI unavailable: {exc}"}
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        code = capability_cli.main(
            [
                "sync",
                "--profile",
                profile,
                "--project-root",
                str(root),
                "--apply",
                "--json",
            ]
        )
    if code != 0:
        return "failed", {"reason": output.getvalue().strip() or f"capability sync exited {code}"}
    return _capability_lock_evidence(root)


def _capability_lock_evidence(root: Path) -> tuple[str, dict]:
    lock_path = root / ".mir" / "capability-lock.json"
    if not lock_path.is_file():
        return "failed", {"reason": "capability sync did not write .mir/capability-lock.json"}
    try:
        lock_data = json.loads(lock_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return "failed", {"reason": f"invalid capability lock: {exc}"}
    if not isinstance(lock_data, dict):
        return "failed", {"reason": "capability lock must be a JSON object"}
    source = lock_data.get("source")
    plugins = lock_data.get("plugins")
    if (
        not isinstance(source, dict)
        or not re.fullmatch(r"[0-9a-f]{40}", str(source.get("commit", "")))
        or not isinstance(plugins, dict)
        or not plugins
    ):
        return "failed", {"reason": "capability lock requires source.commit and non-empty plugins"}
    lock_hash = hashlib.sha256(lock_path.read_bytes()).hexdigest()
    return "ready", {
        "lock_path": ".mir/capability-lock.json",
        "lock_sha256": lock_hash,
        "lock_version": lock_data.get("schema_version"),
        "source_commit": source["commit"],
        "profile": lock_data.get("profile"),
        "selected_plugins": sorted(plugins),
        "selected_agents": sorted(lock_data.get("agents", {})),
        "registration": lock_data.get("registration"),
    }


def _finalize_capabilities(root: Path, prior_receipt: dict | None) -> tuple[str, dict]:
    if not prior_receipt or prior_receipt.get("status") != "restart_required":
        return "failed", {
            "reason": "--finalize requires a prior restart_required bootstrap receipt"
        }
    try:
        from . import capability as capability_cli
    except ImportError as exc:
        return "failed", {"reason": f"capability CLI unavailable: {exc}"}
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        code = capability_cli.main(
            [
                "finalize",
                "--project-root",
                str(root),
                "--apply",
                "--after-restart",
                "--json",
            ]
        )
    if code != 0:
        return "failed", {"reason": output.getvalue().strip() or f"capability status exited {code}"}
    status, evidence = _capability_lock_evidence(root)
    registration = evidence.get("registration")
    if not isinstance(registration, dict) or registration.get("status") != "active":
        return "failed", {"reason": "capability activation lock is not active"}
    return status, evidence


def _validate_architecture_evidence(root: Path) -> tuple[list[str], dict[str, object]]:
    evidence_path = root / "spec" / "bootstrap-evidence.json"
    lock_path = root / ".mir" / "capability-lock.json"
    errors: list[str] = []
    if evidence_path.is_symlink() or not evidence_path.is_file():
        return ["architecture evidence is missing: spec/bootstrap-evidence.json"], {}
    try:
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
        lock = json.loads(lock_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"architecture evidence or capability lock is invalid: {exc}"], {}
    if not isinstance(evidence, dict) or evidence.get("schema_version") != 1:
        errors.append("architecture evidence schema_version must be 1")
        evidence = {}
    sequence = evidence.get("sequence")
    if sequence != list(_ARCHITECTURE_SEQUENCE):
        errors.append("architecture evidence must record design then spec-architect")
    source = lock.get("source") if isinstance(lock, dict) else None
    locked_commit = source.get("commit") if isinstance(source, dict) else None
    if evidence.get("capability_commit") != locked_commit or not isinstance(
        locked_commit, str
    ):
        errors.append("architecture evidence capability_commit does not match the lock")
    outputs = evidence.get("outputs")
    if outputs != list(_ARCHITECTURE_OUTPUTS):
        errors.append("architecture evidence must list the required spec outputs")

    output_hashes: dict[str, str] = {}
    for relative in _ARCHITECTURE_OUTPUTS:
        path = root / relative
        if path.is_symlink() or not path.is_file():
            errors.append(f"architecture output is missing or linked: {relative}")
            continue
        body = path.read_bytes()
        if not body.strip():
            errors.append(f"architecture output is empty: {relative}")
            continue
        output_hashes[relative] = hashlib.sha256(body).hexdigest()
    return errors, {
        "path": "spec/bootstrap-evidence.json",
        "sequence": list(_ARCHITECTURE_SEQUENCE),
        "capability_commit": locked_commit,
        "output_hashes": output_hashes,
    }


def _validate_json_file(path: Path) -> str | None:
    try:
        json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return f"invalid JSON surface {path}: {exc}"
    return None


def _validate_surfaces(root: Path) -> tuple[list[str], dict]:
    errors: list[str] = []
    required_files = (
        "CLAUDE.md",
        "AGENTS.md",
        ".claude/settings.json",
        ".codex/config.toml",
        ".codex/hooks.json",
        ".ai-harness/deny-list.yaml",
        ".claude/agents/main-orchestrator.md",
        ".codex/agents/main-orchestrator.toml",
        "config/sub-agent-policy.json",
        "config/capability-sources.json",
    )
    for relative in required_files:
        if not (root / relative).is_file():
            errors.append(f"required harness surface is missing: {relative}")
    for relative in (
        ".claude/settings.json",
        ".codex/hooks.json",
        "config/sub-agent-policy.json",
        "config/capability-sources.json",
    ):
        path = root / relative
        if path.is_file():
            error = _validate_json_file(path)
            if error:
                errors.append(error)
    if not any((root / ".claude" / "agents").glob("*.md")):
        errors.append("Claude sub-agent registry is empty")
    if not any((root / ".codex" / "agents").glob("*.toml")):
        errors.append("Codex sub-agent registry is empty")
    if not any((root / ".claude" / "hooks").glob("*.sh")):
        errors.append("Claude hook registry is empty")

    settings_path = root / ".claude" / "settings.json"
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
            if not isinstance(settings.get("hooks"), dict) or not settings["hooks"]:
                errors.append(".claude/settings.json has no active hooks")
        except (OSError, json.JSONDecodeError):
            pass
    codex_config = root / ".codex" / "config.toml"
    if codex_config.is_file():
        config_text = codex_config.read_text(encoding="utf-8")
        for field in ("approval_policy", "sandbox_mode"):
            if not re.search(rf"(?m)^{field}\s*=", config_text):
                errors.append(f".codex/config.toml is missing {field}")

    hook_runtime = {
        "kind": "bash",
        "required_on_windows": True,
        "bash": "not_checked",
        "syntax": "not_checked",
    }
    representative_hook = root / ".claude" / "hooks" / "session-start.sh"
    bash_path = shutil.which("bash")
    if platform.system() == "Windows":
        if bash_path is None:
            errors.append("Windows hook runtime requires bash from Git for Windows or WSL on PATH")
            hook_runtime["bash"] = "missing"
        elif not representative_hook.is_file():
            errors.append("representative Bash hook is missing: .claude/hooks/session-start.sh")
        else:
            result = subprocess.run(
                [bash_path, "-n", str(representative_hook)],
                check=False,
                capture_output=True,
                text=True,
            )
            hook_runtime["bash"] = bash_path
            hook_runtime["syntax"] = "ok" if result.returncode == 0 else "failed"
            if result.returncode != 0:
                errors.append(
                    "Windows Bash hook syntax check failed: "
                    + (result.stderr.strip() or f"exit {result.returncode}")
                )
    else:
        hook_runtime["bash"] = bash_path or "not_required_for_bootstrap"
        hook_runtime["syntax"] = "not_required"
    return errors, hook_runtime


def _atomic_write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.close(descriptor)
        temp_path = Path(temp_name)
        temp_path.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        os.replace(temp_path, path)
    finally:
        temp_path = Path(temp_name)
        if temp_path.exists():
            temp_path.unlink()


def _atomic_write_text(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.close(descriptor)
        temp_path = Path(temp_name)
        temp_path.write_text(body, encoding="utf-8")
        os.replace(temp_path, path)
    finally:
        temp_path = Path(temp_name)
        if temp_path.exists():
            temp_path.unlink()


def _stage_memory_db(db_path: Path) -> Path:
    """Create an isolated SQLite snapshot so a failed bootstrap cannot mutate the live index."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, staged_name = tempfile.mkstemp(
        prefix=".memory.bootstrap.", suffix=".db", dir=db_path.parent
    )
    os.close(descriptor)
    staged_path = Path(staged_name)
    if not db_path.exists():
        return staged_path
    source = sqlite3.connect(f"{db_path.as_uri()}?mode=ro", uri=True)
    destination = sqlite3.connect(staged_path)
    try:
        source.backup(destination)
    finally:
        destination.close()
        source.close()
    return staged_path


def _build_projection_updates(root: Path, db_path: Path) -> dict[Path, str]:
    connection = store.connect(db_path)
    try:
        targets = {
            root / "docs" / "memory-map.md": memory_cli._render_memory_map_section(connection.conn),
            root / "tasks" / "lessons.md": memory_cli._render_lessons_section(connection.conn),
        }
    finally:
        connection.conn.close()
    updates: dict[Path, str] = {}
    for path, generated_body in targets.items():
        existing = path.read_text(encoding="utf-8") if path.is_file() else ""
        updates[path] = memory_cli._inject_markers(existing, generated_body)
    return updates


def _emit(ns: argparse.Namespace, receipt: dict) -> None:
    if ns.json:
        print(json.dumps(receipt, sort_keys=True, separators=(",", ":")))
    else:
        print(f"mir bootstrap: {receipt['status']}")
        for error in receipt.get("errors", []):
            print(f"  [not-ready] {error}")
        if receipt["status"] == "restart_required":
            print("  selected global plugins are installed and hash-verified")
            print("  restart Claude Code and begin a new Codex session")
            print("  run mir-core:design then mir-core:spec-architect, then finalize")
        print("  receipt: .mir/bootstrap-receipt.json")


def main(argv: list[str]) -> int:
    ns = _parse(argv)
    root = ns.project_root.expanduser().resolve(strict=False)
    if not root.is_dir():
        print(f"project root is not a directory: {root}", file=sys.stderr)
        return 2
    try:
        slug = _normalise_slug(ns.slug or root.name)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    profile = _PROFILE_ALIASES.get(ns.profile, ns.profile)
    if profile not in _PROFILE_CHOICES:
        print(
            f"unknown profile {ns.profile!r}; choose one of {', '.join(_PROFILE_CHOICES)}",
            file=sys.stderr,
        )
        return 2

    errors: list[str] = []
    invalid_config = False
    capability: dict = {"status": "not_checked"}
    memory_report: dict = {}
    hook_runtime: dict = {}
    projection_updates: dict[Path, str] = {}
    working_db_path: Path | None = None
    staged_db = False
    architecture_evidence: dict[str, object] = {}
    architecture_attested = False
    receipt_path = root / ".mir" / "bootstrap-receipt.json"
    prior_receipt = None
    if receipt_path.is_file():
        try:
            candidate = json.loads(receipt_path.read_text(encoding="utf-8"))
            prior_receipt = candidate if isinstance(candidate, dict) else None
        except (OSError, json.JSONDecodeError):
            prior_receipt = None

    if not (os.environ.get("VIRTUAL_ENV") or sys.prefix != sys.base_prefix):
        errors.append("mir bootstrap must run inside `uv run` after the wrapper executes `uv sync`")

    # Read-only preflight: do not create config, DBs, or projections when the
    # copied harness surfaces or existing authored policy are invalid.
    surface_errors, hook_runtime = _validate_surfaces(root)
    errors.extend(surface_errors)
    try:
        _load_capability_sources(root, profile)
    except (OSError, ValueError) as exc:
        errors.append(str(exc))
        invalid_config = True
    existing_profile = root / ".mir" / "repo-profile.toml"
    if existing_profile.exists():
        try:
            _validate_existing_profile(existing_profile)
        except ValueError as exc:
            errors.append(str(exc))
            invalid_config = True
    existing_harness = root / "harness_a.toml"
    if existing_harness.exists():
        try:
            load_config(root)
        except ConfigLoadError as exc:
            errors.append(str(exc))
            invalid_config = True

    cfg = None
    db_path = root / ".mir" / "memory.db"
    if not errors:
        try:
            _ensure_authored_files(root, slug, profile)
            cfg = load_config(root)
            if not cfg.memory.enabled or not cfg.memory.required:
                errors.append("bootstrap requires memory enabled=true and required=true")
            db_path = resolve_memory_db(root, cfg)
            working_db_path = _stage_memory_db(db_path)
            staged_db = True
        except (ConfigLoadError, OSError) as exc:
            errors.append(str(exc))
            invalid_config = True

    if cfg is not None and not errors:
        try:
            assert working_db_path is not None
            connection = store.connect(working_db_path)
            try:
                store.apply_migrations(connection.conn)
                if cfg.memory.vector_mode == "required":
                    connection.conn.execute(
                        "DELETE FROM external_store_meta "
                        "WHERE key LIKE 'schema_metadata_version:archive:%'"
                    )
                    connection.conn.commit()
            finally:
                connection.conn.close()

            captured = io.StringIO()
            with contextlib.redirect_stdout(captured):
                sync_code = context_cli.main(
                    [
                        "sync",
                        "--db",
                        str(working_db_path),
                        "--project-root",
                        str(root),
                    ]
                )
            if sync_code != 0:
                errors.append(
                    "memory archive sync failed: "
                    + (captured.getvalue().strip() or f"exit {sync_code}")
                )
        except Exception as exc:
            errors.append(f"memory bootstrap failed: {exc}")

        if not errors:
            doctor_code, memory_report = memory_cli.run_doctor(root, db_override=working_db_path)
            if doctor_code != 0:
                errors.extend(
                    f"memory doctor: {message}"
                    for message in memory_report.get("errors", [])
                    if f"memory doctor: {message}" not in errors
                )
            else:
                try:
                    projection_updates = _build_projection_updates(root, working_db_path)
                except Exception as exc:
                    errors.append(f"memory projection preparation failed: {exc}")

    if ns.skip_capability_activation:
        capability = {"status": "skipped", "reason": "explicit test/development boundary"}
        if not ns.allow_incomplete:
            errors.append("capability activation was skipped; bootstrap cannot be ready")
    elif not errors:
        if ns.finalize:
            if not ns.architecture_initialized:
                capability_status = "failed"
                evidence = {
                    "reason": "--finalize requires --architecture-initialized after "
                    "explicit mir-core:design then mir-core:spec-architect execution"
                }
            else:
                architecture_errors, architecture_evidence = _validate_architecture_evidence(root)
                if architecture_errors:
                    capability_status = "failed"
                    evidence = {"reason": "; ".join(architecture_errors)}
                else:
                    capability_status, evidence = _finalize_capabilities(root, prior_receipt)
                    architecture_attested = capability_status == "ready"
            capability = {"status": capability_status, **evidence}
        else:
            capability_status, evidence = _activate_capabilities(root, profile)
            capability = {
                "status": "restart_required" if capability_status == "ready" else capability_status,
                **evidence,
            }
        if capability_status != "ready":
            errors.append(f"capability activation failed: {evidence.get('reason', 'unknown')}")
    else:
        capability = {"status": "not_run", "reason": "preflight or memory failure"}

    unique_errors = list(dict.fromkeys(errors))
    complete = not unique_errors and capability.get("status") == "ready"
    restart_required = not unique_errors and capability.get("status") == "restart_required"
    allowed_incomplete = bool(
        not unique_errors and ns.allow_incomplete and ns.skip_capability_activation
    )
    if not unique_errors and (complete or restart_required or allowed_incomplete):
        try:
            if staged_db:
                assert working_db_path is not None
                for suffix in ("-shm", "-wal"):
                    Path(f"{db_path}{suffix}").unlink(missing_ok=True)
                os.replace(working_db_path, db_path)
                working_db_path = db_path
            for output_path, body in projection_updates.items():
                _atomic_write_text(output_path, body)
        except OSError as exc:
            unique_errors.append(f"memory projection publish failed: {exc}")
            complete = False
            allowed_incomplete = False
    if staged_db and working_db_path is not None and working_db_path != db_path:
        for suffix in ("", "-shm", "-wal"):
            staged_artifact = Path(f"{working_db_path}{suffix}")
            if staged_artifact.exists():
                staged_artifact.unlink()
    if complete:
        status = "ready"
    elif restart_required:
        status = "restart_required"
    else:
        status = "incomplete"
    receipt = {
        "schema_version": 1,
        "status": status,
        "project_slug": slug,
        "profile": profile,
        "platform": {
            "os": platform.system().lower(),
            "release": platform.release(),
            "python": platform.python_version(),
            "hook_runtime": hook_runtime,
        },
        "memory": {
            **memory_report.get("memory", {}),
            "topology": "per_repository_sqlite_fts5",
            "portable_sources": "tracked_markdown_archives_reindexable_cross_machine",
            "shared_database_or_vector_service": "unsupported",
        },
        "vector": memory_report.get("vector", {}),
        "shared_embedding_endpoint": "optional",
        "capabilities": capability,
        "architecture_initialization": {
            "required": True,
            "sequence": list(_ARCHITECTURE_SEQUENCE),
            "applies_regardless_of_first_request_type": True,
            "attested": architecture_attested,
            "evidence": architecture_evidence,
        },
        "errors": unique_errors,
    }
    _atomic_write_json(receipt_path, receipt)
    _emit(ns, receipt)
    if complete or restart_required or allowed_incomplete:
        return 0
    return 2 if invalid_config else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
